- name: osx | reload quicklook
  command: |
    qlmanage -r

- name: osx | disable the sound effects on boot
  command: |
    nvram SystemAudioVolume='%00'
  become: yes

- name: osx | show the ~/Library folder
  command: |
    chflags nohidden ~/Library

- name: osx | restart affected app
  shell: killall {{ item }} || true
  with_items:
    - Dock
    - Finder
    - Mail
    - Safari
    - Transmission
