---
- name: ruby | check rbenv
  command: |
    bash -lc 'which rbenv'
  register: which_rbenv
  ignore_errors: yes

- name: ruby | install rbenv
  command: |
    bash -lc 'anyenv install rbenv'
  when: which_rbenv.rc > 0

- name: ruby | install plugins
  git:
    repo: 'https://github.com/{{ item }}.git'
    dest: '{{ ruby.plugins_dir }}/{{ item.split("/")[1] }}'
  with_items: '{{ ruby.plugins }}'
  when: ruby.plugins_dir and ruby.plugins

- name: ruby | get installed versions
  command: |
    bash -lc 'rbenv versions'
  register: installed_versions

- name: ruby | install dependency
  homebrew:
    name:  '{{ item }}'
    state: present
  with_items:
    - ruby-build
    - openssl
    - readline
  when: ansible_distribution == 'MacOSX'

- name: ruby | get openssl dir
  command: |
    brew --prefix openssl
  register: openssl_dir
  when: ansible_distribution == 'MacOSX'

- name: ruby | get openssl dir
  shell: |
    openssl version -a | sed -n -e 's/^OPENSSLDIR: //p' | tr -d '"'
  register: openssl_dir
  when: ansible_distribution == 'Ubuntu'

- name: ruby | get readline dir
  command: |
    brew --prefix readline
  register: readline_dir
  when: ansible_distribution == 'MacOSX'

- name: ruby | get readline dir
  set_fact:
    readline_dir: /usr/include/readline
  when: ansible_distribution == 'Ubuntu'

- name: ruby | install ruby
  command: |
    bash -lc 'rbenv install {{ item | quote }}'
  environment:
    RUBY_CONFIGURE_OPTS: '--with-openssl-dir={{ openssl_dir.stdout | quote }} --with-readline-dir={{ readline_dir.stdout | quote }}'
  when: |
    ruby.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ ruby.versions }}'

- name: ruby | set global ruby
  command: |
    bash -lc 'rbenv global {{ ruby.versions[0] | quote }}'
  when: ruby.versions
