---
- name: python | activate python {{ version }}
  command: |
    bash -lc 'pyenv global {{ version | quote }}'

- name: python | activate python {{ version }}
  pip:
    name:               '{{ package.name | default(package) }}'
    extra_args:         '{{ package.extra_args | default("") }}'
    state:              latest
    virtualenv_command: pyenv
  become: yes
  with_items: '{{ python.packages }}'
  when: python.packages
  loop_control:
    loop_var: package
